# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMGU7TTfBGYqRTNo7pL_ybmQHdHORzIh

Actividad Nº3, Taller de Programación.
"""

# Ejecicio 1:valor maximo de tres.
def maximo_de_tres(a, b, c):
    return max(a, b, c)

# Ejercicio 2:valor maximo de diez.
def maximo_de_diez():
    numeros = []
    print("Ingrese 10 números:")
    for i in range(10):
        n = int(input(f"Número {i+1}: "))
        numeros.append(n)

    maximo = numeros[0]
    for i in range(1, 10, 3):
        x = numeros[i] if i < 10 else 0
        y = numeros[i+1] if i+1 < 10 else 0
        z = numeros[i+2] if i+2 < 10 else 0
        maximo = max(maximo, maximo_de_tres(x, y, z))

    print(f"El valor máximo es: {maximo}")

# Ejercicio 3:
def cargar_vector(nombre, n):
    vector = []
    print(f"Ingrese {n} números para el vector {nombre}:")
    for i in range(n):
        valor = int(input(f"{nombre}[{i}]: "))
        vector.append(valor)
    return vector

def suma_vector(v):
    return sum(v)

def sumar_vectores(v1, v2):
    return [a + b for a, b in zip(v1, v2)]

def ejercicio_vectores():
    n = int(input("Ingrese la cantidad de elementos para el vector A: "))
    m = int(input("Ingrese la cantidad de elementos para el vector B: "))
    A = cargar_vector("A", n)
    B = cargar_vector("B", m)

    print(f"Suma de A: {suma_vector(A)}")
    print(f"Suma de B: {suma_vector(B)}")

    if n == m:
        suma = sumar_vectores(A, B)
        print("Vector suma A + B:")
        print(suma)
    else:
        print("Los vectores no tienen la misma longitud. No se pueden sumar.")

# Ejercicio 4:
def contar_vocales(palabra):
    vocales = "aeiouáéíóúAEIOUÁÉÍÓÚ"
    return sum(1 for letra in palabra if letra in vocales)

def contar_consonantes(palabra):
    return sum(1 for letra in palabra if letra.isalpha() and letra.lower() not in "aeiouáéíóú")

def analizar_oraciones():
    oracion = input("Ingrese una o más oraciones: ")
    palabras = oracion.split()

    total_vocales = 0
    total_consonantes = 0

    for palabra in palabras:
        total_vocales += contar_vocales(palabra)
        total_consonantes += contar_consonantes(palabra)

    print(f"Total de vocales: {total_vocales}")
    print(f"Total de consonantes: {total_consonantes}")


# Ejercicio 5:
def potencia(x, k):
    return x ** k

def contar_digitos(x):
    return len(str(abs(x)))

def es_capicua(x):
    x_str = str(x)
    return x_str == x_str[::-1]

def menu_opciones_numeros():
    print("\nSubmenú:")
    print("1 - Calcular potencia")
    print("2 - Contar dígitos")
    print("3 - Verificar capicúa")
    opcion = int(input("Ingrese una opción: "))

    if opcion == 1:
        x = int(input("Ingrese base: "))
        k = int(input("Ingrese exponente: "))
        print(f"{x}^{k} = {potencia(x, k)}")
    elif opcion == 2:
        x = int(input("Ingrese número: "))
        print(f"Tiene {contar_digitos(x)} dígitos.")
    elif opcion == 3:
        x = int(input("Ingrese número: "))
        if es_capicua(x):
            print("Es capicúa.")
        else:
            print("No es capicúa.")
    else:
        print("Opción inválida.")

# Ejercicio 6:
def cargar_matriz(filas, columnas):
    matriz = []
    print(f"Ingrese los elementos de la matriz de {filas}x{columnas}:")
    for i in range(filas):
        fila = []
        for j in range(columnas):
            valor = int(input(f"M[{i}][{j}]: "))
            fila.append(valor)
        matriz.append(fila)
    return matriz

def mostrar_matriz(m):
    for fila in m:
        print(fila)

def sumar_matrices(a, b):
    return [[a[i][j] + b[i][j] for j in range(len(a[0]))] for i in range(len(a))]

def multiplicar_matrices(a, b):
    return [[a[i][j] * b[i][j] for j in range(len(a[0]))] for i in range(len(a))]

def operaciones_con_matrices():
    m = int(input("Filas: "))
    n = int(input("Columnas: "))
    print("Matriz A:")
    A = cargar_matriz(m, n)
    print("Matriz B:")
    B = cargar_matriz(m, n)

    print("¿Qué operación desea realizar?")
    print("1 - Suma")
    print("2 - Producto")
    op = int(input("Opción: "))

    if op == 1:
        C = sumar_matrices(A, B)
        print("Resultado (A + B):")
    elif op == 2:
        C = multiplicar_matrices(A, B)
        print("Resultado (A * B):")
    else:
        print("Opción inválida.")
        return

    mostrar_matriz(C)

def menu_principal():
    while True:
        print( "="*50)
        print("           MENÚ PRINCIPAL ")
        print("="*50)
        print("1 - Máximo entre tres números")
        print("2 - Máximo entre 10 números")
        print("3 - Operaciones con dos vectores")
        print("4 - Contar vocales y consonantes en oraciones")
        print("5 - Submenú: Potencia / Dígitos / Capicúa")
        print("6 - Suma o producto de matrices")
        print("0 - Salir")
        print("="*50)

        opcion = input("Seleccione una opción: ")

        if opcion == "1":
            a = int(input("Ingrese primer número: "))
            b = int(input("Ingrese segundo número: "))
            c = int(input("Ingrese tercer número: "))
            print(f"El valor máximo es: {maximo_de_tres(a, b, c)}")
        elif opcion == "2":
            maximo_de_diez()
        elif opcion == "3":
            ejercicio_vectores()
        elif opcion == "4":
            analizar_oraciones()
        elif opcion == "5":
            menu_opciones_numeros()
        elif opcion == "6":
            operaciones_con_matrices()
        elif opcion == "0":
            print("Programa finalizado.")
            break
        else:
            print("Opción inválida. Intente nuevamente.")

menu_principal()